[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[[services]]
name = "portfolio"
source = "."

[services.portfolio.variables]
NODE_ENV = "production"
PORT = "3000"